services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ashquiz
      POSTGRES_PASSWORD: ashquiz
      POSTGRES_DB: ashquiz
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
