/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostRouteRouteImport } from './routes/host/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostIndexRouteImport } from './routes/host/index'
import { Route as HostNicknamesRouteImport } from './routes/host/nicknames'
import { Route as HostPasswordRouteImport } from './routes/host/password'
import { Route as HostUsersRouteImport } from './routes/host/users'
import { Route as PlayPinRouteImport } from './routes/play.$pin'
import { Route as ScreenPinRouteImport } from './routes/screen.$pin'
import { Route as HostGamesIndexRouteImport } from './routes/host/games.index'
import { Route as HostGamesPinRouteImport } from './routes/host/games.$pin'
import { Route as HostQuizzesQuizIdRouteImport } from './routes/host/quizzes.$quizId'
import { Route as HostResultsGameIdRouteImport } from './routes/host/results.$gameId'
import { Route as ScreenResultsGameIdRouteImport } from './routes/screen.results.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRouteRoute = HostRouteRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostRouteRoute,
} as any)
const HostNicknamesRoute = HostNicknamesRouteImport.update({
  id: '/nicknames',
  path: '/nicknames',
  getParentRoute: () => HostRouteRoute,
} as any)
const HostPasswordRoute = HostPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => HostRouteRoute,
} as any)
const HostUsersRoute = HostUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => HostRouteRoute,
} as any)
const PlayPinRoute = PlayPinRouteImport.update({
  id: '/play/$pin',
  path: '/play/$pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenPinRoute = ScreenPinRouteImport.update({
  id: '/screen/$pin',
  path: '/screen/$pin',
  getParentRoute: () => rootRouteImport,
} as any)
const HostGamesIndexRoute = HostGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => HostRouteRoute,
} as any)
const HostGamesPinRoute = HostGamesPinRouteImport.update({
  id: '/games/$pin',
  path: '/games/$pin',
  getParentRoute: () => HostRouteRoute,
} as any)
const HostQuizzesQuizIdRoute = HostQuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => HostRouteRoute,
} as any)
const HostResultsGameIdRoute = HostResultsGameIdRouteImport.update({
  id: '/results/$gameId',
  path: '/results/$gameId',
  getParentRoute: () => HostRouteRoute,
} as any)
const ScreenResultsGameIdRoute = ScreenResultsGameIdRouteImport.update({
  id: '/screen/results/$gameId',
  path: '/screen/results/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host': typeof HostRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/host/nicknames': typeof HostNicknamesRoute
  '/host/password': typeof HostPasswordRoute
  '/host/users': typeof HostUsersRoute
  '/play/$pin': typeof PlayPinRoute
  '/screen/$pin': typeof ScreenPinRoute
  '/host/': typeof HostIndexRoute
  '/host/games/$pin': typeof HostGamesPinRoute
  '/host/quizzes/$quizId': typeof HostQuizzesQuizIdRoute
  '/host/results/$gameId': typeof HostResultsGameIdRoute
  '/screen/results/$gameId': typeof ScreenResultsGameIdRoute
  '/host/games/': typeof HostGamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/host/nicknames': typeof HostNicknamesRoute
  '/host/password': typeof HostPasswordRoute
  '/host/users': typeof HostUsersRoute
  '/play/$pin': typeof PlayPinRoute
  '/screen/$pin': typeof ScreenPinRoute
  '/host': typeof HostIndexRoute
  '/host/games/$pin': typeof HostGamesPinRoute
  '/host/quizzes/$quizId': typeof HostQuizzesQuizIdRoute
  '/host/results/$gameId': typeof HostResultsGameIdRoute
  '/screen/results/$gameId': typeof ScreenResultsGameIdRoute
  '/host/games': typeof HostGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/host': typeof HostRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/host/nicknames': typeof HostNicknamesRoute
  '/host/password': typeof HostPasswordRoute
  '/host/users': typeof HostUsersRoute
  '/play/$pin': typeof PlayPinRoute
  '/screen/$pin': typeof ScreenPinRoute
  '/host/': typeof HostIndexRoute
  '/host/games/$pin': typeof HostGamesPinRoute
  '/host/quizzes/$quizId': typeof HostQuizzesQuizIdRoute
  '/host/results/$gameId': typeof HostResultsGameIdRoute
  '/screen/results/$gameId': typeof ScreenResultsGameIdRoute
  '/host/games/': typeof HostGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/host'
    | '/login'
    | '/host/nicknames'
    | '/host/password'
    | '/host/users'
    | '/play/$pin'
    | '/screen/$pin'
    | '/host/'
    | '/host/games/$pin'
    | '/host/quizzes/$quizId'
    | '/host/results/$gameId'
    | '/screen/results/$gameId'
    | '/host/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/host/nicknames'
    | '/host/password'
    | '/host/users'
    | '/play/$pin'
    | '/screen/$pin'
    | '/host'
    | '/host/games/$pin'
    | '/host/quizzes/$quizId'
    | '/host/results/$gameId'
    | '/screen/results/$gameId'
    | '/host/games'
  id:
    | '__root__'
    | '/'
    | '/host'
    | '/login'
    | '/host/nicknames'
    | '/host/password'
    | '/host/users'
    | '/play/$pin'
    | '/screen/$pin'
    | '/host/'
    | '/host/games/$pin'
    | '/host/quizzes/$quizId'
    | '/host/results/$gameId'
    | '/screen/results/$gameId'
    | '/host/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostRouteRoute: typeof HostRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlayPinRoute: typeof PlayPinRoute
  ScreenPinRoute: typeof ScreenPinRoute
  ScreenResultsGameIdRoute: typeof ScreenResultsGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof HostRouteRoute
    }
    '/host/nicknames': {
      id: '/host/nicknames'
      path: '/nicknames'
      fullPath: '/host/nicknames'
      preLoaderRoute: typeof HostNicknamesRouteImport
      parentRoute: typeof HostRouteRoute
    }
    '/host/password': {
      id: '/host/password'
      path: '/password'
      fullPath: '/host/password'
      preLoaderRoute: typeof HostPasswordRouteImport
      parentRoute: typeof HostRouteRoute
    }
    '/host/users': {
      id: '/host/users'
      path: '/users'
      fullPath: '/host/users'
      preLoaderRoute: typeof HostUsersRouteImport
      parentRoute: typeof HostRouteRoute
    }
    '/play/$pin': {
      id: '/play/$pin'
      path: '/play/$pin'
      fullPath: '/play/$pin'
      preLoaderRoute: typeof PlayPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen/$pin': {
      id: '/screen/$pin'
      path: '/screen/$pin'
      fullPath: '/screen/$pin'
      preLoaderRoute: typeof ScreenPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/games/': {
      id: '/host/games/'
      path: '/games'
      fullPath: '/host/games/'
      preLoaderRoute: typeof HostGamesIndexRouteImport
      parentRoute: typeof HostRouteRoute
    }
    '/host/games/$pin': {
      id: '/host/games/$pin'
      path: '/games/$pin'
      fullPath: '/host/games/$pin'
      preLoaderRoute: typeof HostGamesPinRouteImport
      parentRoute: typeof HostRouteRoute
    }
    '/host/quizzes/$quizId': {
      id: '/host/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/host/quizzes/$quizId'
      preLoaderRoute: typeof HostQuizzesQuizIdRouteImport
      parentRoute: typeof HostRouteRoute
    }
    '/host/results/$gameId': {
      id: '/host/results/$gameId'
      path: '/results/$gameId'
      fullPath: '/host/results/$gameId'
      preLoaderRoute: typeof HostResultsGameIdRouteImport
      parentRoute: typeof HostRouteRoute
    }
    '/screen/results/$gameId': {
      id: '/screen/results/$gameId'
      path: '/screen/results/$gameId'
      fullPath: '/screen/results/$gameId'
      preLoaderRoute: typeof ScreenResultsGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HostRouteRouteChildren {
  HostNicknamesRoute: typeof HostNicknamesRoute
  HostPasswordRoute: typeof HostPasswordRoute
  HostUsersRoute: typeof HostUsersRoute
  HostIndexRoute: typeof HostIndexRoute
  HostGamesPinRoute: typeof HostGamesPinRoute
  HostQuizzesQuizIdRoute: typeof HostQuizzesQuizIdRoute
  HostResultsGameIdRoute: typeof HostResultsGameIdRoute
  HostGamesIndexRoute: typeof HostGamesIndexRoute
}

const HostRouteRouteChildren: HostRouteRouteChildren = {
  HostNicknamesRoute: HostNicknamesRoute,
  HostPasswordRoute: HostPasswordRoute,
  HostUsersRoute: HostUsersRoute,
  HostIndexRoute: HostIndexRoute,
  HostGamesPinRoute: HostGamesPinRoute,
  HostQuizzesQuizIdRoute: HostQuizzesQuizIdRoute,
  HostResultsGameIdRoute: HostResultsGameIdRoute,
  HostGamesIndexRoute: HostGamesIndexRoute,
}

const HostRouteRouteWithChildren = HostRouteRoute._addFileChildren(
  HostRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostRouteRoute: HostRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PlayPinRoute: PlayPinRoute,
  ScreenPinRoute: ScreenPinRoute,
  ScreenResultsGameIdRoute: ScreenResultsGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
